FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y rdiff-backup && \
    pip install flask && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ui/ /app/

EXPOSE 5000
CMD ["python", "app.py"]